### ISSUE TITLE
Custom implementation of Callbackhandler in the case of http-custom-mechanism

### ISSUE THREAD

**Issue by ilapavuluri** [wildfly/wildfly.org#448]
Hi Team,

I am following the below project for  wildfly elytron custom authentication and it is working fine for me.

https://github.com/wildfly/quickstart/tree/main/http-custom-mechanism

I using separate 3rd party application for authentication and authorization, hence I did custom implementation of callbackhandler like this:

public class MyCustomCallbackHandler implements CallbackHandler {
	@Override
    public void handle(Callback[] callbacks) throws IOException, UnsupportedCallbackException {
       
        for (Callback callback : callbacks) {
            if (callback instanceof NameCallback) {
             
                NameCallback nameCallback = (NameCallback) callback;
                username = nameCallback.getName();
            } else if (callback instanceof EvidenceVerifyCallback) {
                 EvidenceVerifyCallback evidenceVerifyCallback = (EvidenceVerifyCallback) callback;
                PasswordGuessEvidence evidence = (PasswordGuessEvidence) evidenceVerifyCallback.getEvidence();
                boolean verified = verifyEvidence(username,evidence);
                    evidenceVerifyCallback.setVerified(verified);

             } else if (callback instanceof AuthorizeCallback) {
                               handleAuthorizeCallback((AuthorizeCallback) callback);
            }
            else {
                        throw new UnsupportedCallbackException(callback, "Unsupported callback type");
            }
        }
    }

    private void handleAuthorizeCallback(AuthorizeCallback callback) {
        callback.setAuthorizedID(authenticationID);
        callback.setAuthorized(true);
    }

    private boolean verifyEvidence(String username,PasswordGuessEvidence evidence) {
	  //Here I am planning to integrate with my 3rd party Identity provider for authentication
       return true;
    }

}
	and in your CustomHeaderHttpAuthenticationMechanism I am sending my above customcallbackhandler, but it is failing at request.authenticationComplete(); with below error
	ERROR [io.undertow.request] (default task-1) UT005023: Exception handling request to /ItpamWildfly28POC-1.0-SNAPSHOT/secured: java.lang.IllegalArgumentException: Parameter 'securityIdentity' may not be null
	at org.wildfly.common@1.6.0.Final//org.wildfly.common.Assert.checkNotNullParamChecked(Assert.java:71)
	at org.wildfly.common@1.6.0.Final//org.wildfly.common.Assert.checkNotNullParam(Assert.java:49)
	at org.wildfly.security.elytron-web.undertow-server@3.0.1.Final//org.wildfly.elytron.web.undertow.server.ElytronAccount.<init>(ElytronAccount.java:50)
	at org.wildfly.security.elytron-web.undertow-server@3.0.1.Final//org.wildfly.elytron.web.undertow.server.ElytronHttpExchange.authenticationComplete(ElytronHttpExchange.java:157)
	at org.wildfly.security.elytron-base@2.1.0.Final//org.wildfly.security.http.HttpAuthenticator$AuthenticationExchange.authenticationComplete(HttpAuthenticator.java:422)
	at org.wildfly.security.elytron-base@2.1.0.Final//org.wildfly.security.http.HttpServerRequest.authenticationComplete(HttpServerRequest.java:129)
	at com.broadcom.itpam.customauth.custom-http-mechanism//com.broadcom.itpam.customauth.CustomHeaderHttpAuthenticationMechanism.evaluateRequest(CustomHeaderHttpAuthenticationMechanism.java:93)

Please let me know if I miss anything here, appreciate your help.

**Comment by yersan** [comment]
Hello @ilapavuluri , this repository (wildfly.org) is the WildFly Website you can see when you access [www.wildfly.org](https://www.wildfly.org/) and it is not meant to raise questions or ask for help about WildFly.

If you are looking for any community help about WildFly or Elytron, you can check the standard channels for that purpose: navigate to www.wildfly.org and take a look at the "Get Help" section at the button of the WildFly Website.
